skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_prediction_market = "8RcTb3UNNY5WzE5t4uFeoe3KndBiQhnjozMPxe9MtGGx"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
